### ISSUE TITLE
Option to disable alternating background color

### ISSUE THREAD

**Issue by chrisetheridge** [datavisyn/chartjs-plugin-barchart-background#3]

**Comment by sgratzl** [comment]
how do you import the plugin? taking a look at the code: 

https://github.com/datavisyn/chartjs-plugin-barchart-background/blob/96d39944073ea6050b3d71314c4cdda3d6c74f5c/src/plugin.js#L72-L75

it will only auto register itself if not imported as a module

**Comment by chrisetheridge** [comment]
i do no import the script into any JS file. i include it via `script` in an HTML page :)

**Comment by sluger** [comment]
I'm not sure if i understand your request correctly, but wouldn't disabling the plugin for individual chart instances solve your problem too? see https://www.chartjs.org/docs/latest/developers/plugins.html#disable-plugins

**Comment by sgratzl** [comment]
https://www.chartjs.org/docs/latest/developers/plugins.html#disable-plugins should do the trick
