### ISSUE TITLE
when i tried to change the mode to even it is not changing color from odd to even

### ISSUE THREAD

**Issue by Cristianopavan** [datavisyn/chartjs-plugin-barchart-background#5]
```
   chartJsPluginBarchartBackground: {
            color: 'grey',
            mode:'even'
          }
```
the background color from odd to even it is changing please help me out

**Comment by sgratzl** [comment]
what do you mean?

when I try: https://codepen.io/sgratzl/pen/ejpNoY?editors=0010

and change the mode from `even` to `odd` the color remains the same
